### ISSUE TITLE
Display Clip ID as button variable

### ISSUE THREAD

**Issue by horuck** [bitfocus/companion-module-hyperdeck#15]
A great feature would be display (polling) the current Clip ID on a streamdeck button.
Since I use 000_clipname, 001_clipname etc for sorting clips in the right order, just showing the first 3 characters (in my case) digits, would be perfect to see on which ID I am currently cueing the deck for playback!

**Comment by bryce-seifert** [comment]
@sphlabs worked on this feature. It's currently waiting for review from @krocheck in pull request https://github.com/bitfocus/companion-module-hyperdeck/pull/14

**Comment by sphlabs** [comment]
This is now implemented in the latest build.
